### PR TITLE
Auto-release when a tag is pushed

### PR DESCRIPTION
**Pull request by ajfloeder**
Documenation should auto-release too.

### CODE REVIEW

**Comment by roehrich-hpe** [comment]
No, we don't want this.  This already has workflows that handle the release.

**Comment by ajfloeder** [comment]
Any idea why the release wasn't auto generated then? I ran the `gh` command to force the release.

**Comment by bdevcich** [comment]
> No, we don't want this. This already has workflows that handle the release.

We have a workflow that publishes the documentation once you've already released, but I don't think we have the automation from tag -> release.

**Comment by roehrich-hpe** [comment]
> Any idea why the release wasn't auto generated then? I ran the `gh` command to force the release.

We may need to do more experimenting here.  But this workflow definitely doesn't belong here, at least not in the same form that we use for code repos.  We should push a tag, and create a release...and that should trigger this: https://github.com/NearNodeFlash/NearNodeFlash.github.io/blob/main/.github/workflows/release.yaml#L3-L5

**Comment by ajfloeder** [comment]
I'm confused as to why the code I copied here is wrong. 

In order to generate release v0.0.10, I had to:
1. create and push the tag
2. (wait for a long time to release no release was coming)
3. manually run `gh release create --generate-notes --verify-tag -p v0.0.10 -t "Release v0.0.10"`

which in turn caused the documentation with the release tag to be published.

**Review by bdevcich — APPROVED** [review]

**Review by roehrich-hpe — APPROVED** [review]

**Pull request merged**
